#!/usr/bin/expect -f
set timeout 2
set passphrase "[lindex $argv 3]"

spawn reprepro --ask-passphrase -b [lindex $argv 0] includedeb [lindex $argv 1] [lindex $argv 2]

#expect {
#        "*passphrase:*" {
#                send -- "$passphrase\r"
#        }
#}
#expect {
#       "*passphrase:*" {
#                send -- "$passphrase\r"
#        }
#}
#interact



## si full screen prompt

expect {
        "*P*" {
                send -- "$passphrase\r"
        }
}
expect {
        "*" {
                send -- "$passphrase\r"
        }
}
interact

